import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  X, 
  Award, 
  CheckCircle2, 
  Clock, 
  Calendar, 
  FileText, 
  Sparkles, 
  Layers, 
  TrendingUp, 
  Bot, 
  Share2, 
  Download,
  ArrowRight,
  ExternalLink,
  Target,
  ChevronRight
} from 'lucide-react';
import { CompletedTrialTask, SkillCard } from '../types';

interface TrialTaskDetailModalProps {
  task: CompletedTrialTask | null;
  isOpen: boolean;
  onClose: () => void;
  onSelectCard?: (card: SkillCard) => void;
  onRetryTask?: (taskId: string) => void;
}

export const TrialTaskDetailModal: React.FC<TrialTaskDetailModalProps> = ({
  task,
  isOpen,
  onClose,
  onSelectCard,
  onRetryTask,
}) => {
  if (!isOpen || !task) return null;

  const handleExportPRD = () => {
    const markdownContent = `# 试路任务产出档案：${task.taskTitle}
**目标岗位**：${task.targetRole}
**完成时间**：${task.completedAt}
**实战综合得分**：${task.score} 分 (${task.grade} 级)

---

## 1. 任务背景与核心使命
- **背景场景**：${task.scenario}
- **核心使命**：${task.mission}

---

## 2. 用户提交的PRD方案与业务设计
### 2.1 核心痛点诊断与归因
${task.userSubmission.coreProblem}

### 2.2 优化方向与落地策略
${task.userSubmission.proposedSolution}

### 2.3 商业价值与ROI算力测算
${task.userSubmission.roiAnalysis}

### 2.4 交付物清单
${task.userSubmission.keyDeliverables.map(d => `- ${d}`).join('\n')}

---

## 3. 智能导师复盘与胜任力雷达评估
> **导师评语**：${task.mentorComment}

### 胜任力得分：
${task.radarScores.map(r => `- **${r.dimension}**：${r.score}分 - ${r.description}`).join('\n')}

---

## 4. 沉淀能力卡牌
${task.earnedCards.map(c => `- **【${c.category}】${c.title}**：${c.description}`).join('\n')}

*Generated by before.choosing 职业探索与试路模拟平台*
`;

    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${task.taskTitle}_实战方案档案.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 overflow-y-auto bg-stone-900/60 backdrop-blur-sm">
        <motion.div
          initial={{ opacity: 0, scale: 0.96, y: 12 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.96, y: 12 }}
          transition={{ duration: 0.25 }}
          className="relative w-full max-w-4xl max-h-[92vh] bg-white rounded-3xl shadow-2xl border border-stone-200/80 flex flex-col overflow-hidden text-stone-900 my-auto"
        >
          {/* Header Banner */}
          <div className="bg-[#FAF9F5] border-b border-stone-200/80 p-5 sm:p-7 flex items-start justify-between gap-4 shrink-0">
            <div className="space-y-2">
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-[11px] font-mono font-bold px-2.5 py-0.5 rounded-full bg-stone-900 text-white uppercase tracking-wider">
                  试路实战档案
                </span>
                <span className="text-xs font-semibold px-2.5 py-0.5 rounded-full bg-amber-100 text-amber-900 border border-amber-200">
                  {task.targetRole}
                </span>
                <span className="text-xs text-stone-500 flex items-center gap-1">
                  <Calendar className="w-3.5 h-3.5" />
                  {task.completedAt}
                </span>
                <span className="text-xs text-stone-500 flex items-center gap-1">
                  <Clock className="w-3.5 h-3.5" />
                  耗时 {task.timeSpent}
                </span>
              </div>
              <h2 className="text-xl sm:text-2xl font-bold text-stone-900 tracking-tight">
                {task.taskTitle}
              </h2>
              <p className="text-xs sm:text-sm text-stone-600 leading-relaxed max-w-2xl">
                {task.summary}
              </p>
            </div>

            {/* Score Pill & Close */}
            <div className="flex items-center gap-3 shrink-0">
              <div className="text-right bg-white p-3 rounded-2xl border border-stone-200 shadow-xs hidden sm:block">
                <div className="text-[10px] text-stone-500 font-medium">实战总评</div>
                <div className="flex items-baseline gap-1 justify-end">
                  <span className="text-2xl font-black text-stone-900">{task.score}</span>
                  <span className="text-xs font-bold text-emerald-600">{task.grade}级</span>
                </div>
              </div>
              <button
                onClick={onClose}
                className="w-9 h-9 rounded-full bg-stone-100 hover:bg-stone-200 text-stone-600 flex items-center justify-center transition cursor-pointer"
                title="关闭"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
          </div>

          {/* Scrollable Body */}
          <div className="p-5 sm:p-8 overflow-y-auto space-y-6 text-sm text-stone-700 leading-relaxed flex-1">
            
            {/* Section 1: Task Mission Context */}
            <div className="p-4 sm:p-5 rounded-2xl bg-amber-50/60 border border-amber-200/70 space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-amber-900">
                <Target className="w-4 h-4 text-amber-700" />
                <span>实战背景与核心使命</span>
              </div>
              <p className="text-xs sm:text-sm text-stone-800">
                <strong className="text-stone-900">业务情境：</strong>{task.scenario}
              </p>
              <p className="text-xs sm:text-sm text-stone-800">
                <strong className="text-stone-900">核心命题：</strong>{task.mission}
              </p>
            </div>

            {/* Section 2: User Submission Content (PRD & Solutions) */}
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b border-stone-100 pb-2">
                <h3 className="text-base font-bold text-stone-900 flex items-center gap-2">
                  <FileText className="w-4 h-4 text-stone-700" />
                  <span>当时提交的方案与交付产出 (PRD Framework)</span>
                </h3>
                <button
                  onClick={handleExportPRD}
                  className="text-xs font-medium text-stone-600 hover:text-stone-900 flex items-center gap-1 px-2.5 py-1 rounded-lg bg-stone-100 hover:bg-stone-200 transition cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>导出 Markdown</span>
                </button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Core Problem */}
                <div className="p-4 rounded-2xl bg-stone-50 border border-stone-200/60 space-y-1.5">
                  <div className="text-xs font-bold text-stone-900 flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-rose-500" />
                    <span>核心痛点归因分析</span>
                  </div>
                  <p className="text-xs sm:text-sm text-stone-700 leading-relaxed whitespace-pre-line">
                    {task.userSubmission.coreProblem}
                  </p>
                </div>

                {/* Proposed Solution */}
                <div className="p-4 rounded-2xl bg-stone-50 border border-stone-200/60 space-y-1.5">
                  <div className="text-xs font-bold text-stone-900 flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-emerald-500" />
                    <span>产品与交互解决方案</span>
                  </div>
                  <p className="text-xs sm:text-sm text-stone-700 leading-relaxed whitespace-pre-line">
                    {task.userSubmission.proposedSolution}
                  </p>
                </div>
              </div>

              {/* ROI & Deliverables */}
              <div className="p-4 rounded-2xl bg-stone-50 border border-stone-200/60 space-y-2">
                <div className="text-xs font-bold text-stone-900 flex items-center gap-1.5">
                  <TrendingUp className="w-3.5 h-3.5 text-blue-600" />
                  <span>商业价值与ROI算力测算</span>
                </div>
                <p className="text-xs sm:text-sm text-stone-700 leading-relaxed">
                  {task.userSubmission.roiAnalysis}
                </p>

                <div className="pt-2 border-t border-stone-200/60 flex flex-wrap items-center gap-2">
                  <span className="text-[11px] font-bold text-stone-500">产出清单：</span>
                  {task.userSubmission.keyDeliverables.map((item, idx) => (
                    <span key={idx} className="text-xs px-2.5 py-0.5 rounded-full bg-white border border-stone-200 text-stone-800 font-medium">
                      {item}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Section 3: Mentor Feedback & Radar */}
            <div className="space-y-4">
              <h3 className="text-base font-bold text-stone-900 flex items-center gap-2 border-b border-stone-100 pb-2">
                <Bot className="w-4 h-4 text-purple-600" />
                <span>智能导师评价与胜任力雷达打分</span>
              </h3>

              {/* Mentor quote */}
              <div className="p-4 rounded-2xl bg-purple-50/70 border border-purple-200/70 flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-purple-600 text-white flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">
                  教练
                </div>
                <div className="space-y-1">
                  <div className="text-xs font-bold text-purple-950">任务教练复盘简评</div>
                  <p className="text-xs sm:text-sm text-purple-900 leading-relaxed">
                    {task.mentorComment}
                  </p>
                </div>
              </div>

              {/* Radar Scores Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {task.radarScores.map((scoreItem, idx) => (
                  <div key={idx} className="p-3.5 rounded-2xl bg-white border border-stone-200/80 shadow-2xs space-y-1">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold text-stone-900">{scoreItem.dimension}</span>
                      <span className="text-xs font-mono font-black text-amber-600">{scoreItem.score} 分</span>
                    </div>
                    <div className="w-full bg-stone-100 rounded-full h-1.5 overflow-hidden">
                      <div 
                        className="bg-amber-500 h-full rounded-full transition-all"
                        style={{ width: `${scoreItem.score}%` }}
                      />
                    </div>
                    <p className="text-[11px] text-stone-500 pt-0.5 leading-snug">{scoreItem.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Section 4: Earned Skill Cards */}
            <div className="space-y-3">
              <h3 className="text-base font-bold text-stone-900 flex items-center gap-2 border-b border-stone-100 pb-2">
                <Sparkles className="w-4 h-4 text-emerald-600" />
                <span>本次试路任务沉淀的能力卡（{task.earnedCards.length} 张）</span>
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {task.earnedCards.map((card) => (
                  <div
                    key={card.id}
                    onClick={() => onSelectCard && onSelectCard(card)}
                    className="p-3.5 rounded-2xl bg-stone-50 hover:bg-stone-100 border border-stone-200 transition cursor-pointer group space-y-1.5"
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-white border border-stone-200 text-stone-700">
                        {card.category}
                      </span>
                      <ChevronRight className="w-3.5 h-3.5 text-stone-400 group-hover:translate-x-0.5 transition" />
                    </div>
                    <div className="text-xs font-bold text-stone-900 group-hover:text-amber-700 transition">
                      {card.title}
                    </div>
                    <p className="text-[11px] text-stone-600 line-clamp-2 leading-relaxed">
                      {card.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Section 5: User Reflection */}
            {task.reflectionNotes && (
              <div className="p-4 rounded-2xl bg-stone-100/80 border border-stone-200 text-xs text-stone-700 space-y-1">
                <span className="font-bold text-stone-900">💡 个人复盘与经验沉淀：</span>
                <p className="leading-relaxed">{task.reflectionNotes}</p>
              </div>
            )}

          </div>

          {/* Footer Actions */}
          <div className="p-4 sm:p-5 bg-[#FAF9F5] border-t border-stone-200/80 flex flex-wrap items-center justify-between gap-3 shrink-0">
            <div className="text-xs text-stone-500">
              任务已永久归档至你的个人职业画像中，可随时回看与导出
            </div>
            <div className="flex items-center gap-2.5">
              <button
                onClick={handleExportPRD}
                className="px-4 py-2 text-xs font-medium rounded-full bg-stone-100 hover:bg-stone-200 text-stone-800 transition cursor-pointer flex items-center gap-1.5"
              >
                <Download className="w-3.5 h-3.5" />
                <span>导出完整方案</span>
              </button>
              <button
                onClick={() => {
                  onClose();
                  if (onRetryTask) onRetryTask(task.id);
                }}
                className="craft-btn-black px-5 py-2 text-xs font-bold cursor-pointer flex items-center gap-1.5"
              >
                <span>重新演练此任务</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>

        </motion.div>
      </div>
    </AnimatePresence>
  );
};
